/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/menu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Menu
         * @description Меню с применённым стоп-листом (источник — внешнее меню iiko).
         */
        get: operations["get_menu_api_menu_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/eta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pickup Eta
         * @description Предпросмотр «ближайшего времени» самовывоза для чекаута.
         */
        get: operations["pickup_eta_api_orders_eta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Checkout
         * @description Чекаут: доставка / самовывоз ко времени / за столом.
         *
         *     Гостевой чекаут — всегда доступен, авторизация не требуется.
         *     За столом источник состава — общая корзина стола на сервере,
         *     request.items игнорируется (все гости наполняют одну корзину).
         */
        post: operations["checkout_api_orders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Order */
        get: operations["get_order_api_orders__order_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/delivery/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Suggest Address
         * @description Подсказки адресов для чекаута (DaData или мок, пока нет ключа).
         */
        get: operations["suggest_address_api_delivery_suggest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/delivery/zones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Zones
         * @description Полигоны зон для карты на странице «Доставка».
         */
        get: operations["get_zones_api_delivery_zones_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/delivery/check-address": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check Address
         * @description Проверка адреса до оплаты. Координаты — из DaData-подсказок на фронте.
         */
        post: operations["check_address_api_delivery_check_address_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/booking/sections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sections
         * @description Схема залов со столами для интерактивной карты (координаты — из iiko).
         *
         *     TODO на реальном iiko: занятость по выбранному времени (?date=), а не
         *     только текущая — доступность слотов посчитаем из списка резервов.
         */
        get: operations["get_sections_api_booking_sections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/booking/reserve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Reserve */
        post: operations["create_reserve_api_booking_reserve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tables/{table_code}/cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Table Cart
         * @description Общая корзина стола — одна на всех гостей, вошедших по QR.
         */
        get: operations["get_table_cart_api_tables__table_code__cart_get"];
        put?: never;
        /**
         * Update Table Cart
         * @description Гость добавляет/меняет позицию; остальные видят по SSE (канал table-cart).
         */
        post: operations["update_table_cart_api_tables__table_code__cart_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/request-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request Code
         * @description Отправить код подтверждения (заглушка: подходит 0000).
         */
        post: operations["request_code_api_auth_request_code_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify */
        post: operations["verify_api_auth_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/account/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Order History
         * @description История заказов гостя (по телефону) со снапшотами состава.
         *
         *     Позже дополним историей из iiko (deliveries/by_delivery_date_and_phone) —
         *     там видны и заказы, сделанные не через сайт.
         */
        get: operations["order_history_api_account_orders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/webhooks/iiko": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Iiko Webhook */
        post: operations["iiko_webhook_api_webhooks_iiko_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/webhooks/telegram": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Telegram Webhook
         * @description Апдейты Telegram-бота смен (кнопки в личке).
         */
        post: operations["telegram_webhook_api_webhooks_telegram_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/webhooks/payment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Payment Webhook
         * @description Колбэк эквайринга; формат зависит от банка (адаптер), пока каркас.
         */
        post: operations["payment_webhook_api_webhooks_payment_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AccountOrder
         * @description Заказ в истории ЛК — со снапшотом состава для повтора в 1 клик.
         */
        AccountOrder: {
            /** Id */
            id: string;
            mode: components["schemas"]["OrderMode"];
            status: components["schemas"]["OrderStatus"];
            /** Payment Status */
            payment_status: string;
            /** Amount */
            amount: number;
            /** Items */
            items: components["schemas"]["CartItem"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** AddressCheckRequest */
        AddressCheckRequest: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
        };
        /** AddressCheckResult */
        AddressCheckResult: {
            /** In Zone */
            in_zone: boolean;
            zone?: components["schemas"]["DeliveryZone"] | null;
        };
        /**
         * AddressSuggestion
         * @description Подсказка адреса (DaData или заглушка) с координатами для проверки зоны.
         */
        AddressSuggestion: {
            /** Value */
            value: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
        };
        /** AuthMe */
        AuthMe: {
            /** Phone */
            phone: string;
        };
        /** AuthPhone */
        AuthPhone: {
            /** Phone */
            phone: string;
        };
        /** AuthVerify */
        AuthVerify: {
            /** Phone */
            phone: string;
            /** Code */
            code: string;
        };
        /** CartItem */
        CartItem: {
            /** Item Id */
            item_id: string;
            /**
             * Quantity
             * @default 1
             */
            quantity: number;
        };
        /** CheckoutRequest */
        CheckoutRequest: {
            mode: components["schemas"]["OrderMode"];
            /** Items */
            items: components["schemas"]["CartItem"][];
            /** Phone */
            phone?: string | null;
            /** Address */
            address?: string | null;
            /** Desired Time */
            desired_time?: string | null;
            /** Table Code */
            table_code?: string | null;
            /**
             * Comment
             * @default
             */
            comment: string;
        };
        /** DeliveryZone */
        DeliveryZone: {
            /** Name */
            name: string;
            /** Polygon */
            polygon: number[][];
            /**
             * Min Order
             * @default 0
             */
            min_order: number;
            /**
             * Delivery Price
             * @default 0
             */
            delivery_price: number;
        };
        /**
         * EtaView
         * @description Предпросмотр времени готовности самовывоза (до оформления заказа).
         */
        EtaView: {
            /** Eta Minutes */
            eta_minutes: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Menu */
        Menu: {
            /** Categories */
            categories: components["schemas"]["MenuCategory"][];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** MenuCategory */
        MenuCategory: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Items */
            items: components["schemas"]["MenuItem"][];
        };
        /** MenuItem */
        MenuItem: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Price */
            price: number;
            /** Image Url */
            image_url?: string | null;
            /**
             * Allergens
             * @default []
             */
            allergens: string[];
            /**
             * Tags
             * @default []
             */
            tags: string[];
            nutrition?: components["schemas"]["Nutrition"] | null;
            /**
             * In Stop List
             * @default false
             */
            in_stop_list: boolean;
        };
        /**
         * Nutrition
         * @description КБЖУ на порцию (данные из внешнего меню iiko).
         */
        Nutrition: {
            /** Kcal */
            kcal: number;
            /** Proteins */
            proteins: number;
            /** Fats */
            fats: number;
            /** Carbs */
            carbs: number;
        };
        /**
         * OrderMode
         * @enum {string}
         */
        OrderMode: "delivery" | "pickup" | "table";
        /**
         * OrderStatus
         * @enum {string}
         */
        OrderStatus: "new" | "cooking" | "ready" | "on_the_way" | "closed" | "cancelled";
        /** OrderView */
        OrderView: {
            /** Id */
            id: string;
            mode: components["schemas"]["OrderMode"];
            status: components["schemas"]["OrderStatus"];
            /** Payment Status */
            payment_status: string;
            /** Payment Url */
            payment_url?: string | null;
            /** Eta Minutes */
            eta_minutes?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ReserveRequest */
        ReserveRequest: {
            /** Table Id */
            table_id: string;
            /** Phone */
            phone: string;
            /** Guests */
            guests: number;
            /**
             * Time
             * Format: date-time
             */
            time: string;
        };
        /** ReserveView */
        ReserveView: {
            /** Id */
            id: string;
            /** Table Id */
            table_id: string;
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /** Status */
            status: string;
        };
        /** Section */
        Section: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Tables */
            tables: components["schemas"]["Table"][];
        };
        /** Table */
        Table: {
            /** Id */
            id: string;
            /** Code */
            code: string;
            /** Number */
            number: number;
            /** Seats */
            seats: number;
            /** X */
            x: number;
            /** Y */
            y: number;
            /**
             * Occupied
             * @default false
             */
            occupied: boolean;
        };
        /** TableCart */
        TableCart: {
            /** Table Code */
            table_code: string;
            /** Lines */
            lines: components["schemas"]["TableCartLine"][];
            /** Total */
            total: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** TableCartLine */
        TableCartLine: {
            /** Item Id */
            item_id: string;
            /** Name */
            name: string;
            /** Price */
            price: number;
            /** Quantity */
            quantity: number;
            /** Guest */
            guest: string;
        };
        /** TableCartUpdate */
        TableCartUpdate: {
            /** Item Id */
            item_id: string;
            /** Quantity */
            quantity: number;
            /**
             * Guest
             * @default Гость
             */
            guest: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_menu_api_menu_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Menu"];
                };
            };
        };
    };
    pickup_eta_api_orders_eta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EtaView"];
                };
            };
        };
    };
    checkout_api_orders_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_order_api_orders__order_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suggest_address_api_delivery_suggest_get: {
        parameters: {
            query: {
                query: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddressSuggestion"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_zones_api_delivery_zones_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryZone"][];
                };
            };
        };
    };
    check_address_api_delivery_check_address_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddressCheckRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddressCheckResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sections_api_booking_sections_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Section"][];
                };
            };
        };
    };
    create_reserve_api_booking_reserve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReserveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReserveView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_table_cart_api_tables__table_code__cart_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                table_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableCart"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_table_cart_api_tables__table_code__cart_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                table_code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TableCartUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableCart"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_code_api_auth_request_code_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthPhone"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_api_auth_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthVerify"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthMe"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthMe"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    order_history_api_account_orders_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountOrder"][];
                };
            };
        };
    };
    iiko_webhook_api_webhooks_iiko_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                }[];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    telegram_webhook_api_webhooks_telegram_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    payment_webhook_api_webhooks_payment_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
