/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/menu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Menu
         * @description Меню с применённым стоп-листом (источник — внешнее меню iiko).
         */
        get: operations["get_menu_api_menu_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Checkout
         * @description Чекаут: доставка / самовывоз ко времени / за столом.
         *
         *     Гостевой чекаут — всегда доступен, авторизация не требуется.
         */
        post: operations["checkout_api_orders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Order */
        get: operations["get_order_api_orders__order_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/delivery/zones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Zones
         * @description Полигоны зон для карты на странице «Доставка».
         */
        get: operations["get_zones_api_delivery_zones_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/delivery/check-address": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check Address
         * @description Проверка адреса до оплаты. Координаты — из DaData-подсказок на фронте.
         */
        post: operations["check_address_api_delivery_check_address_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/booking/sections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sections
         * @description Схема залов со столами для интерактивной карты (координаты — из iiko).
         */
        get: operations["get_sections_api_booking_sections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/booking/reserve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Reserve */
        post: operations["create_reserve_api_booking_reserve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/webhooks/iiko": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Iiko Webhook */
        post: operations["iiko_webhook_api_webhooks_iiko_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/webhooks/payment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Payment Webhook
         * @description Колбэк эквайринга; формат зависит от банка (адаптер), пока каркас.
         */
        post: operations["payment_webhook_api_webhooks_payment_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddressCheckRequest */
        AddressCheckRequest: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
        };
        /** AddressCheckResult */
        AddressCheckResult: {
            /** In Zone */
            in_zone: boolean;
            zone?: components["schemas"]["DeliveryZone"] | null;
        };
        /** CartItem */
        CartItem: {
            /** Item Id */
            item_id: string;
            /**
             * Quantity
             * @default 1
             */
            quantity: number;
        };
        /** CheckoutRequest */
        CheckoutRequest: {
            mode: components["schemas"]["OrderMode"];
            /** Items */
            items: components["schemas"]["CartItem"][];
            /** Phone */
            phone?: string | null;
            /** Address */
            address?: string | null;
            /** Desired Time */
            desired_time?: string | null;
            /** Table Code */
            table_code?: string | null;
            /**
             * Comment
             * @default
             */
            comment: string;
        };
        /** DeliveryZone */
        DeliveryZone: {
            /** Name */
            name: string;
            /** Polygon */
            polygon: number[][];
            /**
             * Min Order
             * @default 0
             */
            min_order: number;
            /**
             * Delivery Price
             * @default 0
             */
            delivery_price: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Menu */
        Menu: {
            /** Categories */
            categories: components["schemas"]["MenuCategory"][];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** MenuCategory */
        MenuCategory: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Items */
            items: components["schemas"]["MenuItem"][];
        };
        /** MenuItem */
        MenuItem: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Price */
            price: number;
            /** Image Url */
            image_url?: string | null;
            /**
             * Allergens
             * @default []
             */
            allergens: string[];
            /**
             * Tags
             * @default []
             */
            tags: string[];
            nutrition?: components["schemas"]["Nutrition"] | null;
            /**
             * In Stop List
             * @default false
             */
            in_stop_list: boolean;
        };
        /**
         * Nutrition
         * @description КБЖУ на порцию (данные из внешнего меню iiko).
         */
        Nutrition: {
            /** Kcal */
            kcal: number;
            /** Proteins */
            proteins: number;
            /** Fats */
            fats: number;
            /** Carbs */
            carbs: number;
        };
        /**
         * OrderMode
         * @enum {string}
         */
        OrderMode: "delivery" | "pickup" | "table";
        /**
         * OrderStatus
         * @enum {string}
         */
        OrderStatus: "new" | "cooking" | "ready" | "on_the_way" | "closed" | "cancelled";
        /** OrderView */
        OrderView: {
            /** Id */
            id: string;
            mode: components["schemas"]["OrderMode"];
            status: components["schemas"]["OrderStatus"];
            /** Payment Status */
            payment_status: string;
            /** Payment Url */
            payment_url?: string | null;
            /** Eta Minutes */
            eta_minutes?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ReserveRequest */
        ReserveRequest: {
            /** Table Id */
            table_id: string;
            /** Phone */
            phone: string;
            /** Guests */
            guests: number;
            /**
             * Time
             * Format: date-time
             */
            time: string;
        };
        /** ReserveView */
        ReserveView: {
            /** Id */
            id: string;
            /** Table Id */
            table_id: string;
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /** Status */
            status: string;
        };
        /** Section */
        Section: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Tables */
            tables: components["schemas"]["Table"][];
        };
        /** Table */
        Table: {
            /** Id */
            id: string;
            /** Code */
            code: string;
            /** Number */
            number: number;
            /** Seats */
            seats: number;
            /** X */
            x: number;
            /** Y */
            y: number;
            /**
             * Occupied
             * @default false
             */
            occupied: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_menu_api_menu_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Menu"];
                };
            };
        };
    };
    checkout_api_orders_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_order_api_orders__order_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_zones_api_delivery_zones_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryZone"][];
                };
            };
        };
    };
    check_address_api_delivery_check_address_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddressCheckRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddressCheckResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sections_api_booking_sections_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Section"][];
                };
            };
        };
    };
    create_reserve_api_booking_reserve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReserveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReserveView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    iiko_webhook_api_webhooks_iiko_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                }[];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    payment_webhook_api_webhooks_payment_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
